CREATE TABLE YORUMLAR (
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    VIDEO_ID INT,
    YAZAR_KULLANICI_ID INT,
    METIN VARCHAR,
    DURUM VARCHAR,
    OLUSTURULMA_ZAMANI DATETIME,
    GUNCELLEME_ZAMANI DATETIME
);
