CREATE TABLE VIDEOLAR (
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    BASLIK VARCHAR,
    ACIKLAMA VARCHAR,
    KANAL_ID INT,
    YUKLEYICI_ID INT,
    ETIKETLER VARCHAR ARRAY,
    DURUM VARCHAR,
    YUKLEME_ZAMANI DATETIME,
    GUNCELLEME_ZAMANI DATETIME
);
