CREATE TABLE KULLANICILAR (
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    EMAIL VARCHAR,
    SIFRE VARCHAR,
    AD VARCHAR,
    SOYAD VARCHAR,
    PROFIL_RESMI_URL VARCHAR,
    KAYIT_TARIHI DATETIME
);

CREATE TABLE ROLLER (
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    ISIM VARCHAR,
    IZINLER VARCHAR ARRAY,
    KULLANICI_ID INT
);
